"""Add is_trainer and is_admin to User

Revision ID: 608e7362f2df
Revises: 5cf2fae90a10
Create Date: 2026-03-21 13:22:55.439297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608e7362f2df'
down_revision = '5cf2fae90a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trainer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_trainer')

    # ### end Alembic commands ###
