"""Add Trainer Assignment Many-to-Many

Revision ID: dbabdd379023
Revises: 608e7362f2df
Create Date: 2026-03-21 13:52:46.972210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbabdd379023'
down_revision = '608e7362f2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_assignment',
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trainee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('trainer_id', 'trainee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_assignment')
    # ### end Alembic commands ###
